package projectfiles

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/eslam-mahmoud/go-ai-agent/internal/domain"
)

func TestRenderExactEmptySnapshot(t *testing.T) {
	project := fixtureProject()
	files, err := Render(project, nil)
	if err != nil {
		t.Fatal(err)
	}

	wantYAML := `version: 1
project:
    id: 7
    repository: owner/repo
    name: Madar
    goal: Ship v2
    scope: ""
    state: initializing
    health: on-track
    parent_issue_number: 0
    current_task_id: null
    current_plan_version: 0
    architecture_version: 0
    release_target: ""
    release_readiness: ""
    last_manager_review_at: null
    created_at: "2026-07-24T01:02:03.123456789Z"
    updated_at: "2026-07-24T02:03:04Z"
backlog: []
`
	if got := string(files.ProjectYAML); got != wantYAML {
		t.Errorf("project YAML mismatch\n--- got ---\n%s--- want ---\n%s", got, wantYAML)
	}

	wantPlan := `# Project Plan: Madar

> Generated by Madar from durable project state. Do not edit by hand.

## Goal

Ship v2

## Scope

-

## Project Status

| Repository | State | Health | Release target | Release readiness |
| --- | --- | --- | --- | --- |
| owner/repo | initializing | on-track | - | - |

## Ordered Backlog

| Seq | Issue | Status | Priority | Task | Goal | Release blocker |
| ---: | ---: | --- | ---: | --- | --- | :---: |
| - | - | - | - | _No tasks_ | - | - |
`
	if got := string(files.PlanMarkdown); got != wantPlan {
		t.Errorf("plan Markdown mismatch\n--- got ---\n%s--- want ---\n%s", got, wantPlan)
	}
}

func TestRenderIsIdempotentOrderedAndEscaped(t *testing.T) {
	project := fixtureProject()
	project.Name = "Madar\nV2"
	project.ReleaseTarget = "v2 | stable"
	project.ReleaseReadiness = "tests\\green"
	reviewedAt := time.Date(2026, 7, 24, 3, 4, 5, 0, time.FixedZone("offset", 3*60*60))
	project.LastManagerReviewAt = &reviewedAt

	discoveryID := int64(88)
	second := domain.NewTask(project.ID, "Second | task", "Keep \\ paths\nstable")
	second.ID = 12
	second.Sequence = 2
	second.Priority = 5
	second.SourceDiscoveryID = &discoveryID
	first := domain.NewTask(project.ID, "First task", "Run first")
	first.ID = 11
	first.Sequence = 1
	first.IssueNumber = 42
	first.BlocksRelease = true

	files, err := Render(project, []*domain.Task{second, first})
	if err != nil {
		t.Fatal(err)
	}
	again, err := Render(project, []*domain.Task{second, first})
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(files.ProjectYAML, again.ProjectYAML) ||
		!bytes.Equal(files.PlanMarkdown, again.PlanMarkdown) {
		t.Fatal("equal snapshots did not produce byte-identical files")
	}

	yamlText := string(files.ProjectYAML)
	if strings.Index(yamlText, "id: 11") >= strings.Index(yamlText, "id: 12") {
		t.Fatalf("YAML backlog is not sequence ordered:\n%s", yamlText)
	}
	for _, want := range []string{
		`last_manager_review_at: "2026-07-24T00:04:05Z"`,
		"source_discovery_id: 88",
		"blocks_release: true",
	} {
		if !strings.Contains(yamlText, want) {
			t.Errorf("YAML missing %q:\n%s", want, yamlText)
		}
	}

	planText := string(files.PlanMarkdown)
	if strings.Index(planText, "First task") >= strings.Index(planText, `Second \| task`) {
		t.Fatalf("Markdown backlog is not sequence ordered:\n%s", planText)
	}
	for _, want := range []string{
		"# Project Plan: Madar V2",
		`v2 \| stable`,
		`tests\\green`,
		`Second \| task`,
		`Keep \\ paths<br>stable`,
		"| 1 | 42 | proposed | 0 | First task | Run first | yes |",
	} {
		if !strings.Contains(planText, want) {
			t.Errorf("Markdown missing %q:\n%s", want, planText)
		}
	}
}

func TestRenderRejectsInvalidSnapshots(t *testing.T) {
	project := fixtureProject()
	validTask := domain.NewTask(project.ID, "Task", "Goal")
	validTask.ID = 1
	validTask.Sequence = 1

	tests := []struct {
		name    string
		project *domain.Project
		tasks   []*domain.Task
	}{
		{name: "nil project", project: nil},
		{name: "unpersisted project", project: withProjectID(fixtureProject(), 0)},
		{name: "missing project timestamp", project: withoutCreatedAt(fixtureProject())},
		{name: "nil task", project: project, tasks: []*domain.Task{nil}},
		{name: "unpersisted task", project: project, tasks: []*domain.Task{domain.NewTask(project.ID, "Task", "Goal")}},
		{name: "wrong project", project: project, tasks: []*domain.Task{withTaskProject(validTask, 99)}},
		{name: "duplicate sequence", project: project, tasks: []*domain.Task{validTask, cloneTask(validTask, 2)}},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			_, err := Render(tc.project, tc.tasks)
			if !errors.Is(err, ErrInvalidSnapshot) {
				t.Fatalf("error = %v, want ErrInvalidSnapshot", err)
			}
		})
	}
}

func TestWriteCreatesAndAtomicallyReplacesFiles(t *testing.T) {
	workspace := t.TempDir()
	first := Files{
		ProjectYAML:  []byte("version: 1\n"),
		PlanMarkdown: []byte("# First\n"),
	}
	if err := Write(workspace, first); err != nil {
		t.Fatal(err)
	}

	projectPath := filepath.Join(workspace, DirectoryName, ProjectFileName)
	planPath := filepath.Join(workspace, DirectoryName, PlanFileName)
	assertFile(t, projectPath, first.ProjectYAML)
	assertFile(t, planPath, first.PlanMarkdown)

	second := Files{
		ProjectYAML:  []byte("version: 2\n"),
		PlanMarkdown: []byte("# Second\n"),
	}
	if err := Write(workspace, second); err != nil {
		t.Fatal(err)
	}
	assertFile(t, projectPath, second.ProjectYAML)
	assertFile(t, planPath, second.PlanMarkdown)

	entries, err := os.ReadDir(filepath.Join(workspace, DirectoryName))
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 2 {
		t.Fatalf("output directory contains temporary files: %#v", entries)
	}
	for _, path := range []string{projectPath, planPath} {
		info, err := os.Stat(path)
		if err != nil {
			t.Fatal(err)
		}
		if got := info.Mode().Perm(); got != 0o644 {
			t.Errorf("%s mode = %o, want 644", path, got)
		}
	}
}

func TestWriteRejectsMissingAndUnsafeDirectoriesWithoutOutput(t *testing.T) {
	t.Run("missing workspace", func(t *testing.T) {
		parent := t.TempDir()
		workspace := filepath.Join(parent, "missing")
		err := Write(workspace, Files{
			ProjectYAML:  []byte("yaml"),
			PlanMarkdown: []byte("markdown"),
		})
		if err == nil {
			t.Fatal("expected missing workspace error")
		}
		if _, statErr := os.Stat(workspace); !errors.Is(statErr, os.ErrNotExist) {
			t.Fatalf("missing workspace was created: %v", statErr)
		}
	})

	t.Run("symlinked output directory", func(t *testing.T) {
		workspace := t.TempDir()
		outside := t.TempDir()
		if err := os.Symlink(outside, filepath.Join(workspace, DirectoryName)); err != nil {
			t.Fatal(err)
		}
		err := Write(workspace, Files{
			ProjectYAML:  []byte("yaml"),
			PlanMarkdown: []byte("markdown"),
		})
		if !errors.Is(err, ErrUnsafeDirectory) {
			t.Fatalf("error = %v, want ErrUnsafeDirectory", err)
		}
		entries, err := os.ReadDir(outside)
		if err != nil {
			t.Fatal(err)
		}
		if len(entries) != 0 {
			t.Fatalf("wrote through symlink: %#v", entries)
		}
	})

	t.Run("unsafe second target", func(t *testing.T) {
		workspace := t.TempDir()
		outputDir := filepath.Join(workspace, DirectoryName)
		if err := os.Mkdir(outputDir, 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.Mkdir(filepath.Join(outputDir, PlanFileName), 0o755); err != nil {
			t.Fatal(err)
		}
		err := Write(workspace, Files{
			ProjectYAML:  []byte("yaml"),
			PlanMarkdown: []byte("markdown"),
		})
		if !errors.Is(err, ErrUnsafeDirectory) {
			t.Fatalf("error = %v, want ErrUnsafeDirectory", err)
		}
		if _, statErr := os.Stat(filepath.Join(outputDir, ProjectFileName)); !errors.Is(statErr, os.ErrNotExist) {
			t.Fatalf("first target was partially written: %v", statErr)
		}
	})
}

func fixtureProject() *domain.Project {
	project := domain.NewProject("owner/repo", "Madar", "Ship v2", "")
	project.ID = 7
	project.CreatedAt = time.Date(2026, 7, 24, 1, 2, 3, 123456789, time.UTC)
	project.UpdatedAt = time.Date(2026, 7, 24, 2, 3, 4, 0, time.UTC)
	return project
}

func withProjectID(project *domain.Project, id int64) *domain.Project {
	project.ID = id
	return project
}

func withoutCreatedAt(project *domain.Project) *domain.Project {
	project.CreatedAt = time.Time{}
	return project
}

func withTaskProject(task *domain.Task, projectID int64) *domain.Task {
	copied := *task
	copied.ProjectID = projectID
	return &copied
}

func cloneTask(task *domain.Task, id int64) *domain.Task {
	copied := *task
	copied.ID = id
	return &copied
}

func assertFile(t *testing.T, path string, want []byte) {
	t.Helper()
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want) {
		t.Errorf("%s = %q, want %q", path, got, want)
	}
}
