package architecturedocs

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"unicode"
)

const generatedNotice = "_Generated by Madar. Edits outside the marked sections are preserved._"

// sortedComponents copies and orders components by name so rendering never
// depends on the order the provider happened to return.
func sortedComponents(components []Component) []Component {
	ordered := append([]Component(nil), components...)
	sort.SliceStable(ordered, func(i, j int) bool {
		return ordered[i].Name < ordered[j].Name
	})
	return ordered
}

func sortedDependencies(dependencies []Dependency) []Dependency {
	ordered := append([]Dependency(nil), dependencies...)
	sort.SliceStable(ordered, func(i, j int) bool {
		if ordered[i].From != ordered[j].From {
			return ordered[i].From < ordered[j].From
		}
		return ordered[i].To < ordered[j].To
	})
	return ordered
}

func sortedRisks(risks []Risk) []Risk {
	ordered := append([]Risk(nil), risks...)
	sort.SliceStable(ordered, func(i, j int) bool {
		return ordered[i].Title < ordered[j].Title
	})
	return ordered
}

func renderOverview(project Project, proposal *Proposal) []byte {
	var output bytes.Buffer
	fmt.Fprintf(&output, "# %s — Architecture Overview\n\n", inline(project.Name))
	if goal := inline(project.Goal); goal != "" {
		fmt.Fprintf(&output, "**Goal:** %s\n\n", goal)
	}
	if repo := inline(project.Repo); repo != "" {
		fmt.Fprintf(&output, "**Repository:** `%s`\n\n", repo)
	}
	output.WriteString("## Summary\n\n")
	output.WriteString(paragraph(proposal.Summary))
	output.WriteString("\n\n## Components\n\n")
	components := sortedComponents(proposal.Components)
	if len(components) == 0 {
		output.WriteString("_No components recorded._\n")
	} else {
		for _, component := range components {
			fmt.Fprintf(&output, "- **%s** — %s\n",
				inline(component.Name), inline(component.Responsibility))
		}
	}
	output.WriteString("\n## Cross-cutting Risks\n\n")
	risks := sortedRisks(proposal.Risks)
	if len(risks) == 0 {
		output.WriteString("_None recorded._\n")
	} else {
		for _, risk := range risks {
			fmt.Fprintf(&output, "- **%s** — %s", inline(risk.Title), inline(risk.Impact))
			if affected := inlineList(risk.Components); affected != "" {
				fmt.Fprintf(&output, " (affects %s)", affected)
			}
			output.WriteString("\n")
		}
	}
	fmt.Fprintf(&output, "\n%s\n", generatedNotice)
	return output.Bytes()
}

func renderComponents(proposal *Proposal) []byte {
	var output bytes.Buffer
	output.WriteString("# Components\n\n")
	components := sortedComponents(proposal.Components)
	if len(components) == 0 {
		output.WriteString("_No components recorded._\n\n")
		fmt.Fprintf(&output, "%s\n", generatedNotice)
		return output.Bytes()
	}
	output.WriteString("| Component | Responsibility | Depends on |\n")
	output.WriteString("| --- | --- | --- |\n")
	for _, component := range components {
		fmt.Fprintf(&output, "| %s | %s | %s |\n",
			cell(component.Name),
			cell(component.Responsibility),
			cellOrDash(inlineList(component.DependsOn)),
		)
	}
	output.WriteString("\n")
	for _, component := range components {
		fmt.Fprintf(&output, "## %s\n\n%s\n\n",
			inline(component.Name), paragraph(component.Responsibility))
	}
	fmt.Fprintf(&output, "%s\n", generatedNotice)
	return output.Bytes()
}

func renderDataFlow(proposal *Proposal) []byte {
	var output bytes.Buffer
	output.WriteString("# Data Flow\n\n")
	dependencies := sortedDependencies(proposal.Dependencies)
	if len(dependencies) == 0 {
		output.WriteString("_No dependencies recorded._\n\n")
		fmt.Fprintf(&output, "%s\n", generatedNotice)
		return output.Bytes()
	}
	output.WriteString("```mermaid\ngraph TD\n")
	for _, dependency := range dependencies {
		fmt.Fprintf(&output, "    %s --> %s\n",
			identifier(dependency.From), identifier(dependency.To))
	}
	output.WriteString("```\n\n## Dependencies\n\n")
	for _, dependency := range dependencies {
		fmt.Fprintf(&output, "- `%s` → `%s` — %s\n",
			inline(dependency.From), inline(dependency.To), inline(dependency.Reason))
	}
	fmt.Fprintf(&output, "\n%s\n", generatedNotice)
	return output.Bytes()
}

func renderDecision(number int, decision Decision) []byte {
	var output bytes.Buffer
	fmt.Fprintf(&output, "# ADR-%03d: %s\n\n", number, inline(decision.Title))
	output.WriteString("## Status\n\nAccepted\n\n## Decision\n\n")
	output.WriteString(paragraph(decision.Decision))
	output.WriteString("\n\n## Rationale\n\n")
	output.WriteString(paragraph(decision.Rationale))
	output.WriteString("\n\n## Alternatives considered\n\n")
	if len(decision.Alternatives) == 0 {
		output.WriteString("_None recorded._\n")
	} else {
		for _, alternative := range decision.Alternatives {
			fmt.Fprintf(&output, "- %s\n", inline(alternative))
		}
	}
	output.WriteString("\n## Consequences\n\n")
	if consequences := paragraph(decision.Consequences); consequences != "" {
		output.WriteString(consequences)
		output.WriteString("\n")
	} else {
		output.WriteString("_None recorded._\n")
	}
	fmt.Fprintf(&output, "\n%s\n", generatedNotice)
	return output.Bytes()
}

// renderAgentsSection produces only Madar's marked section; the surrounding
// file belongs to the humans who wrote it.
func renderAgentsSection(project Project, proposal *Proposal) string {
	var output bytes.Buffer
	output.WriteString(AgentsStartMarker)
	output.WriteString("\n## Project\n\n")
	fmt.Fprintf(&output, "- **Name:** %s\n", inlineOrDash(project.Name))
	fmt.Fprintf(&output, "- **Goal:** %s\n", inlineOrDash(project.Goal))
	fmt.Fprintf(&output, "- **Repository:** %s\n", inlineOrDash(project.Repo))
	output.WriteString("\n## Architecture\n\n")
	output.WriteString(paragraph(proposal.Summary))
	output.WriteString("\n\n### Components\n\n")
	components := sortedComponents(proposal.Components)
	if len(components) == 0 {
		output.WriteString("_No components recorded._\n")
	} else {
		for _, component := range components {
			fmt.Fprintf(&output, "- **%s** — %s\n",
				inline(component.Name), inline(component.Responsibility))
		}
	}
	output.WriteString("\n### Reference\n\n")
	fmt.Fprintf(&output, "- Overview: `%s`\n", OverviewFile)
	fmt.Fprintf(&output, "- Components: `%s`\n", ComponentsFile)
	fmt.Fprintf(&output, "- Data flow: `%s`\n", DataFlowFile)
	fmt.Fprintf(&output, "- Decisions: `%s/`\n", DecisionsDir)
	output.WriteString("\n")
	output.WriteString(AgentsEndMarker)
	return output.String()
}

// slugify produces the stable file-name identity of a decision, so the same
// decision is never filed twice under different names.
func slugify(value string) string {
	var builder strings.Builder
	pendingDash := false
	for _, symbol := range strings.ToLower(strings.TrimSpace(value)) {
		switch {
		case unicode.IsLetter(symbol) || unicode.IsDigit(symbol):
			if pendingDash && builder.Len() > 0 {
				builder.WriteByte('-')
			}
			pendingDash = false
			builder.WriteRune(symbol)
		default:
			pendingDash = true
		}
	}
	slug := builder.String()
	const maxSlug = 60
	if len(slug) > maxSlug {
		slug = strings.TrimRight(slug[:maxSlug], "-")
	}
	return slug
}

// identifier renders a mermaid-safe node name.
func identifier(value string) string {
	slug := slugify(value)
	if slug == "" {
		return "unknown"
	}
	return strings.ReplaceAll(slug, "-", "_")
}

func inline(value string) string {
	return strings.Join(strings.Fields(escapeMarkers(value)), " ")
}

func inlineOrDash(value string) string {
	if collapsed := inline(value); collapsed != "" {
		return collapsed
	}
	return "-"
}

func inlineList(values []string) string {
	parts := make([]string, 0, len(values))
	for _, value := range values {
		if collapsed := inline(value); collapsed != "" {
			parts = append(parts, "`"+collapsed+"`")
		}
	}
	sort.Strings(parts)
	return strings.Join(parts, ", ")
}

func paragraph(value string) string {
	normalized := strings.ReplaceAll(escapeMarkers(value), "\r\n", "\n")
	return strings.TrimSpace(normalized)
}

func cell(value string) string {
	collapsed := inline(value)
	collapsed = strings.ReplaceAll(collapsed, "\\", "\\\\")
	return strings.ReplaceAll(collapsed, "|", "\\|")
}

func cellOrDash(value string) string {
	if strings.TrimSpace(value) == "" {
		return "-"
	}
	return strings.ReplaceAll(value, "|", "\\|")
}

// escapeMarkers stops proposal text from forging Madar's section boundaries.
func escapeMarkers(value string) string {
	return strings.NewReplacer(
		AgentsStartMarker, "&lt;!-- madar:agents:start --&gt;",
		AgentsEndMarker, "&lt;!-- madar:agents:end --&gt;",
	).Replace(value)
}
